// File generated by FlutterFire configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYScYUe1hyyX4i0LtDZIIzODpJt5DrFZ4',
    appId: '1:821098798913:web:122556f2d193b7134bcbc0',
    messagingSenderId: '821098798913',
    projectId: 'n8n-api-503416',
    storageBucket: 'n8n-api-503416.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYScYUe1hyyX4i0LtDZIIzODpJt5DrFZ4',
    appId: '1:821098798913:android:122556f2d193b7134bcbc0',
    messagingSenderId: '821098798913',
    projectId: 'n8n-api-503416',
    storageBucket: 'n8n-api-503416.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYScYUe1hyyX4i0LtDZIIzODpJt5DrFZ4',
    appId: '1:821098798913:ios:122556f2d193b7134bcbc0',
    messagingSenderId: '821098798913',
    projectId: 'n8n-api-503416',
    storageBucket: 'n8n-api-503416.firebasestorage.app',
    iosBundleId: 'com.juansadigital.tivo.tivo',
  );
}
